version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 7s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - HW_33_todolist_pg_data:/var/lib/postgresql/data/

  run_migrations:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  bot:
    image: redkrane/diploma-todolist:latest
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/app/.env
    command: python manage.py runbot

  api:
    build: .
    image: redkrane/diploma-todolist:latest
    env_file: .env
    environment:
      DB_HOST: db
      DEBUG: true
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    volumes:
      - ./core:/opt/app/core/
      - ./goals:/opt/app/goals/
      - ./bot:/opt/app/bot/
      - ./todolist:/opt/app/todolist/

  collect_static:
    build: .
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/app/static/

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

volumes:
  HW_33_todolist_pg_data:
  django_static:
